name: Delete Chunks

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Delete Chunk Files
        uses: test-room-7/action-delete-files@v2.0.0
        with:
          files: "gcc_part_* ccache_part_* chunk_part_* *b64.txt"
          commit-message: "clean: remove all compiler chunk files"